language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

env:
  - PHPUNIT=5.0.* COMPOSER_OPTS="--prefer-lowest"
  - PHPUNIT=5.1.*
  - PHPUNIT=5.2.*
  - PHPUNIT=5.3.*
  - PHPUNIT=5.4.*
  - PHPUNIT=5.5.*
  - PHPUNIT=5.6.*
  - PHPUNIT=5.7.*
  - PHPUNIT=6.0.*
  - PHPUNIT=6.1.*
  - PHPUNIT=6.2.*
  - PHPUNIT=6.3.*
  - PHPUNIT=6.4.*
  - PHPUNIT=6.5.*

matrix:
  fast_finish: true

before_script:
  - phpenv config-rm xdebug.ini || true
  - composer self-update
  - composer -n --prefer-dist require phpunit/phpunit:${PHPUNIT} ${COMPOSER_OPTS}

script:
  - composer test
