language: php
dist: trusty

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true

before_script:
  - phpenv config-rm xdebug.ini || true
  - composer self-update
  - composer remove phpunit/phpunit
  - composer -n --prefer-dist install

script:
  - composer test
